import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
print(torch.__version__)

2.7.1+cu128


## INTRODUCTION TO TENSORS

### CREATING TENSORS

In [10]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [11]:
scalar.ndim

0

#### scalars have zero dimension


In [13]:
scalar.item()
# GET TENSOR BACK AS python int

7

In [14]:
#vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [15]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [18]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
MATRIX.ndim

2

In [20]:
MATRIX[0]

tensor([7, 8])

In [21]:
MATRIX[1]


tensor([ 9, 10])

In [22]:
MATRIX.shape

torch.Size([2, 2])

In [23]:
TENSOR = torch.tensor([[[1,2,3,],
                        [4,5,6],
                        [2,5,8]]])

TENSOR
                        

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 5, 8]]])

In [24]:
TENSOR.shape


torch.Size([1, 3, 3])

In [25]:
TENSOR.ndim

3

#### basically TENSOR.shape is telling that the tensor contains 1 matrix having 3 rows and three columns

In [26]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [2, 5, 8]])

In [29]:
TENSOR1 = torch.tensor([[[1,2,3,],
                        [4,5,6],
                        [2,5,8]],
                        [[1,2,3,],
                        [4,5,6],
                        [2,5,8]]])


In [30]:
TENSOR1.shape

torch.Size([2, 3, 3])

#### tensor basically can be anything from collection of matrix to a zero dimensional entity called scalar

#### so basically Tensors and Matrix are represented by uppercase letters and scalers are represented by lowercase letters

### Random tensors

random tensors are imp becuase the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbners to better represent the data

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [31]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)


In [33]:
random_tensor

tensor([[0.2913, 0.1326, 0.5995, 0.5639],
        [0.7573, 0.7804, 0.8672, 0.9941],
        [0.1021, 0.7141, 0.8407, 0.2907]])

In [34]:
# create a random tensor of size (10,3,4)
random_tensor1 = torch.rand(10,3,4)
random_tensor1

tensor([[[0.6650, 0.4780, 0.2039, 0.7094],
         [0.8941, 0.1434, 0.2623, 0.5395],
         [0.7437, 0.3477, 0.5498, 0.3491]],

        [[0.5432, 0.1472, 0.4981, 0.5806],
         [0.1599, 0.6005, 0.4945, 0.0091],
         [0.7384, 0.3710, 0.6643, 0.9122]],

        [[0.0662, 0.3750, 0.8598, 0.2581],
         [0.7384, 0.0882, 0.3049, 0.0825],
         [0.5004, 0.1862, 0.7680, 0.2203]],

        [[0.6372, 0.1450, 0.3744, 0.4752],
         [0.3959, 0.7872, 0.3957, 0.9791],
         [0.6994, 0.6801, 0.6538, 0.5366]],

        [[0.7700, 0.1693, 0.7448, 0.8369],
         [0.3673, 0.9911, 0.3519, 0.3274],
         [0.9282, 0.6705, 0.9096, 0.3117]],

        [[0.9705, 0.8804, 0.7230, 0.3490],
         [0.0344, 0.8763, 0.0183, 0.4967],
         [0.5980, 0.3561, 0.2732, 0.3990]],

        [[0.9460, 0.4118, 0.4328, 0.4604],
         [0.0704, 0.5403, 0.3216, 0.4671],
         [0.6940, 0.1102, 0.2607, 0.9093]],

        [[0.6717, 0.5819, 0.1909, 0.0710],
         [0.3022, 0.4619, 0.9564, 0.7978

In [37]:
#create a random tensor with similar shape to an image tensor 
random_image_size_tensor = torch.rand(size=(3,224,224)) # colour channel R,G,B,height,widht
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### zeros and ones

In [38]:
# create a tensor of all zeroes
zeros = torch.zeros(3,4)
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
# create a tensor of all ones
ones = torch.ones(3,4)
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
ones.dtype

torch.float32

#### torch.float32 is the default data type of pytorch

## creating a range of tensor and tensors-like

In [41]:
torch.range(0,10)

C:\Users\idcoc\AppData\Local\Temp\ipykernel_16392\497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [42]:
torch.arange(4,10)

tensor([4, 5, 6, 7, 8, 9])

In [43]:
one_to_ten = torch.arange(start=0, end = 1000,step = 77)

In [44]:
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [47]:
#creating tensors like
N_zeroes = torch.zeros_like(input = one_to_ten)

In [49]:
N_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
N_abc = torch.rand_like(input = one_to_ten)
N_abc

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [52]:
N_abc = torch.rand_like(one_to_ten.float())
N_abc

tensor([0.9751, 0.6601, 0.9911, 0.3551, 0.7651, 0.4561, 0.2795, 0.9126, 0.3619,
        0.9639, 0.2164, 0.6012, 0.9752])

In [53]:
N_abc = torch.rand_like(one_to_ten, dtype=torch.float32)
N_abc

tensor([0.3807, 0.2378, 0.8374, 0.0863, 0.3983, 0.1453, 0.2733, 0.1144, 0.4413,
        0.9391, 0.8595, 0.1736, 0.2361])

### tensor datatypes

**Note:** tensor datatypes is one of the 3 big errors you'll run into with pytorch and deep learning:
1. Tensors not right datatype
2.  tensors not right shape
3.  tensors not on the right device  

In [55]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,# what data type the tensor is default is float32
                               device=None,# what device is your tensor on
                               requires_grad=False)# whether or not to track gradients
float_32_tensor 


tensor([3., 6., 9.])

In [56]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [57]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [58]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [59]:
int_32_tensor*float_32_tensor

tensor([ 9., 36., 81.])

### getting information from tensors 

1. Tensors not right datatype - to get datatype use `tensor.dtype`
2. tensors not right shape - to get the shape use `tensor.shape`
3. tensors not on the right device to get device use `tensor.device`


In [61]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.4057, 0.1979, 0.7820, 0.3897],
        [0.3302, 0.0199, 0.2472, 0.9734],
        [0.0809, 0.6608, 0.1595, 0.0813]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### manipulating tensors ( tensor operationsd)

these includes
* addition
* subtraction
* multiplication (element wise)
* division
* matrix multiplication)

In [62]:
# create a tensor
tensor = torch.tensor([1,2,3])

In [63]:
tensor +10

tensor([11, 12, 13])

In [64]:
tensor*10

tensor([10, 20, 30])

In [65]:
tensor 

tensor([1, 2, 3])

In [66]:
tensor = tensor *10

In [67]:
tensor

tensor([10, 20, 30])

In [68]:
tensor -10

tensor([ 0, 10, 20])

#### try out pytorch in-buil function

In [70]:
torch.mul(tensor,10)

tensor([100, 200, 300])

In [71]:
torch.add(tensor,10)

tensor([20, 30, 40])

### matrix multiplication 

there are two ways of multiplication in ML

* element-wise
* matrix multiplication(dot product)

there are two mains rules
* firstly the inner dimensions must match
* the resulting matrix have shape of outer dimensions 




In [74]:
#element wise multiplication 
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [75]:
torch.matmul(tensor,tensor)

tensor(1400)

In [79]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: total: 0 ns
Wall time: 1.01 ms


In [80]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(1400)

In [81]:
tensor @ tensor

tensor(1400)

## one of the most common errors in deep learning:shape errors

In [82]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,2],
                         [3,4],
                         [5,5]])
torch.mm(tensor_A,tensor_B) #same as torch.matmul
                         

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

to fix out tensor shape issues , we can malipulate the shape of one of our tensors using transpose 


In [83]:
tensor_B.T

tensor([[7, 3, 5],
        [2, 4, 5]])

In [84]:
tensor_B

tensor([[7, 2],
        [3, 4],
        [5, 5]])

In [85]:
torch.mm(tensor_A,tensor_B.T)

tensor([[11, 11, 15],
        [29, 25, 35],
        [47, 39, 55]])

## Finding the min,max,mean,sum,etc(tensor aggregation)

In [86]:
x = torch.arange(0,100,10)

In [87]:
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [88]:
torch.min(x)


tensor(0)

In [89]:
x.max()

tensor(90)

In [90]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [92]:
# torch.mean() requires floast32 dtype to work
x.type(torch.float32).mean()

tensor(45.)

In [96]:
#find the position in tensor that has the minimum valye with argmin() -> return index value where the min value is present same for argmax()
print(x.argmin())
print(x.argmax())

tensor(0)
tensor(9)


In [97]:
x[9]

tensor(90)

## Reshaping,stacking , squeezing and unsqueezing tensors

* reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as original tensor
* stacking- combining multiple tensors on top of each other (vstack) or side by side (hstack)
* squeeze - removes all `1` dimeions from a tensor
* unsqueeze - add a `1` dimension to a target tesor
* premute return a view of the input with dimensions permuted(swapped) in a certain way)
* 

In [98]:
x = torch.arange(1.0,10.0)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [99]:
x_reshaped = x.reshape(1,7)

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [100]:
x_reshaped = x.reshape(1,9)

In [101]:
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [102]:
x_reshaped = x.reshape(9,1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [103]:
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [104]:
z = x.view(3,3)

In [105]:
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [106]:
# changing z changes x ( beacuse a view of tensor shares sa=ame memory as original tensor)
z[:,0] = 5 
z,x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [107]:
#stack tensor on top of it
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [109]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [110]:
x_stacked = torch.stack([x,x,x,x],dim=2)
x_stacked

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [117]:
# torch.squeeze removes all the single dimensions from a target tensor)
x_reshaped = x_reshaped.reshape(1,9)

In [118]:
x_reshaped.shape

torch.Size([1, 9])

In [119]:
x_reshaped

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [122]:
x_reshaped.squeeze().shape

torch.Size([9])

In [123]:
x_reshaped.shape

torch.Size([1, 9])

In [125]:
x_unsqueezed = x_reshaped.unsqueeze(dim=0)

In [126]:
x_unsqueezed

tensor([[[5., 2., 3., 5., 5., 6., 5., 8., 9.]]])

In [127]:
x_unsqueezed.shape

torch.Size([1, 1, 9])

In [128]:
x_unsqueezed = x_reshaped.unsqueeze(dim=1)


In [129]:
x_unsqueezed

tensor([[[5., 2., 3., 5., 5., 6., 5., 8., 9.]]])

In [130]:
x_unsqueezed.shape

torch.Size([1, 1, 9])

In [131]:
x_unsqueezed = x_reshaped.unsqueeze(dim=2)

In [132]:
x_unsqueezed.shape


torch.Size([1, 9, 1])

In [133]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [134]:
x_original[0,0,0] = 2334 
x_original[0,0,0],x_permuted[0,0,0]

(tensor(2334.), tensor(2334.))

## Indexing(selecting data from tensors)
Indexing with pytorch is similar to indexing with numpy

In [136]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [137]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [138]:
x[0][0]

tensor([1, 2, 3])

In [139]:
x[0][0][0]

tensor(1)

In [140]:
# you can also use ":" to select all of the target dimension
x[:,0]

tensor([[1, 2, 3]])

In [142]:
# get all values of 0 and 1st dimension but only 1st index of 2nd 
x[:,:,1]

tensor([[2, 5, 8]])

In [144]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [146]:
# index to return 9
print(x[0][2][2])

# index on x to retunr 3 6 9
print(x[:,:,2])


tensor(9)
tensor([[3, 6, 9]])


## Pytorch tensors and numpy

Numpy is popular thats why pytorch has functionality to interact with it 

* data in numpy,want in pytorch tensor
* numpy has float.64 has default dtype and pytorch has float.32

In [147]:
arr = np.arange(1.0,8.0)


In [149]:
tensor = torch.from_numpy(arr).type(torch.float32)

In [151]:
arr,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [154]:
# change of value of array wont impact tensor takes storage in new memory
arr = arr +1
arr,tensor

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [155]:
numpy_tensor = tensor.numpy()
numpy_tensor, tensor

(array([1., 2., 3., 4., 5., 6., 7.], dtype=float32),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

## Reproducibility (trying to take random out of random)

to reduce randomness in neural networks and pytorch comes the concept of **random seed**

Essentially what the random seed does is flavour the randomness



In [157]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.4300, 0.8248, 0.4410, 0.4050],
        [0.3561, 0.8631, 0.7399, 0.9222],
        [0.0407, 0.5853, 0.1989, 0.8076]])
tensor([[0.2312, 0.4843, 0.3022, 0.3141],
        [0.2577, 0.1535, 0.1216, 0.3892],
        [0.6523, 0.5476, 0.4082, 0.4710]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [159]:
#SET THE RANDOM SEED
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [161]:
#SET THE RANDOM SEED AND manual_seed REQUIRES same code line on DIFFERENT CODE BLOCKS
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensor and pytorch objects on the gpus

In [163]:
!nvidia-smi

Sun Jul 20 15:12:22 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 576.40                 Driver Version: 576.40         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   50C    P8              6W /   50W |    1073MiB /   4096MiB |     40%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### ITS A GOOD PRACTICE TO SETUP A AGNOSTIC DEVICE

In [164]:
#  device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [165]:
torch.cuda.device_count()

1

## Putting tensors (and models) on the gpu

In [167]:
# create a tensor (default on cpu)

tensor = torch.tensor([1,2,3])

print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [168]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### moving tensor back to the cpu


In [170]:
# if tensor on gpu cant transfom it to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [173]:
tensor_back_on_cpu = tensor_on_gpu.cpu()

In [174]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()

In [175]:
tensor_back_on_cpu

array([1, 2, 3])