In [2]:
import torch

In [7]:
scalar = torch.tensor(7)

In [8]:

scalar.ndim

0

In [9]:
scalar.item()

7

In [10]:
vector =torch.tensor([1, 2, 3, 4, 5])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([5])

In [19]:
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [20]:
tensor 

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [21]:
tensor.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                       [7,8,9]],
                      [[10,11,12],
                       [13,14,15],
                       [16,17,18]],
                      [[19,20,21],
                       [22,23,24],
                       [25,26,27]]])

In [17]:
TENSOR.shape

torch.Size([3, 3, 3])

In [18]:
TENSOR.ndim

3

In [22]:
random_tensor = torch.rand(3, 4)

In [23]:
random_tensor

tensor([[0.3401, 0.2735, 0.4191, 0.8236],
        [0.9703, 0.9025, 0.5148, 0.9129],
        [0.7371, 0.9311, 0.7051, 0.8199]])

In [ ]:
random_tensor = torch.rand( 10,3, 4)

In [ ]:
random_

In [25]:
random_tensor

tensor([[[0.5163, 0.3100, 0.9642, 0.5168],
         [0.1008, 0.4559, 0.9077, 0.5241],
         [0.7603, 0.6594, 0.2906, 0.7343]],

        [[0.5020, 0.8883, 0.9743, 0.9619],
         [0.2077, 0.0392, 0.7121, 0.5445],
         [0.7705, 0.6680, 0.8187, 0.6864]],

        [[0.4727, 0.2332, 0.6585, 0.8411],
         [0.5362, 0.1390, 0.7849, 0.3810],
         [0.6341, 0.4928, 0.5455, 0.5797]],

        [[0.3408, 0.9553, 0.2532, 0.1635],
         [0.6291, 0.8009, 0.3226, 0.5575],
         [0.4102, 0.1562, 0.4833, 0.4661]],

        [[0.1649, 0.8707, 0.7011, 0.0367],
         [0.4345, 0.0533, 0.7659, 0.8479],
         [0.8717, 0.5577, 0.4603, 0.0170]],

        [[0.1522, 0.9945, 0.5452, 0.7542],
         [0.5702, 0.6356, 0.9639, 0.0208],
         [0.6957, 0.8032, 0.1294, 0.1692]],

        [[0.7198, 0.0437, 0.0863, 0.7814],
         [0.9726, 0.9460, 0.4886, 0.6470],
         [0.6120, 0.3143, 0.1708, 0.5597]],

        [[0.5454, 0.0714, 0.0249, 0.6859],
         [0.0416, 0.2438, 0.0916, 0.7710

In [28]:
image_tensor = torch.rand(3, 224, 224) 

In [27]:
image_tensor

tensor([[[0.4098, 0.0891, 0.3782,  ..., 0.5563, 0.3578, 0.9060],
         [0.8942, 0.0843, 0.0044,  ..., 0.7407, 0.8264, 0.0336],
         [0.1103, 0.3315, 0.7370,  ..., 0.2334, 0.7437, 0.3323],
         ...,
         [0.3357, 0.0710, 0.4659,  ..., 0.2070, 0.9466, 0.8367],
         [0.3450, 0.7999, 0.5961,  ..., 0.6423, 0.4634, 0.0824],
         [0.8966, 0.7825, 0.9982,  ..., 0.1840, 0.1445, 0.4382]],

        [[0.3768, 0.7788, 0.5281,  ..., 0.0114, 0.6077, 0.3209],
         [0.5665, 0.7241, 0.9541,  ..., 0.1277, 0.4811, 0.2510],
         [0.0965, 0.5176, 0.8994,  ..., 0.2340, 0.6843, 0.2786],
         ...,
         [0.2449, 0.3537, 0.7639,  ..., 0.4659, 0.1751, 0.2864],
         [0.6910, 0.8351, 0.1354,  ..., 0.1625, 0.4532, 0.0358],
         [0.5741, 0.0885, 0.2006,  ..., 0.6403, 0.3824, 0.8470]],

        [[0.9638, 0.1878, 0.2555,  ..., 0.8487, 0.8261, 0.6048],
         [0.8390, 0.9391, 0.9381,  ..., 0.3929, 0.0952, 0.4788],
         [0.1652, 0.5967, 0.8026,  ..., 0.7119, 0.2430, 0.

In [ ]:
random_tensor = torch.rand(2,3,4,5)
random_tensor

tensor([[[[0.2898, 0.1748, 0.8492, 0.1546, 0.6591],
          [0.8363, 0.1722, 0.3583, 0.2093, 0.7705],
          [0.3321, 0.9112, 0.4503, 0.1868, 0.7353],
          [0.7307, 0.8422, 0.6563, 0.4422, 0.5467]],

         [[0.1397, 0.9777, 0.3028, 0.7128, 0.8856],
          [0.7547, 0.5236, 0.2350, 0.4257, 0.2077],
          [0.1065, 0.5603, 0.2655, 0.8065, 0.0027],
          [0.7295, 0.0113, 0.8825, 0.7962, 0.4605]],

         [[0.8235, 0.5149, 0.7254, 0.7546, 0.4758],
          [0.1845, 0.3255, 0.8285, 0.3577, 0.7273],
          [0.7511, 0.1540, 0.1031, 0.9379, 0.9333],
          [0.6657, 0.8074, 0.2154, 0.0517, 0.5587]]],


        [[[0.4959, 0.4261, 0.3736, 0.6580, 0.6914],
          [0.6550, 0.0860, 0.7970, 0.5611, 0.3018],
          [0.0996, 0.0774, 0.7793, 0.2290, 0.5529],
          [0.9685, 0.6825, 0.6274, 0.8550, 0.5340]],

         [[0.1413, 0.2575, 0.5645, 0.3788, 0.1820],
          [0.9834, 0.0523, 0.2859, 0.2032, 0.6110],
          [0.2369, 0.8674, 0.1135, 0.9397, 0.5880],
  

In [30]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
zeros.device

device(type='cpu')

In [33]:
!nvidia-smi

Sat Feb 21 19:53:31 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 591.74                 Driver Version: 591.74         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   49C    P5              9W /   50W |    1540MiB /   4096MiB |     27%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [34]:
ones.to("cuda")

AssertionError: Torch not compiled with CUDA enabled

In [35]:
print(torch.__version__)

2.10.0+cpu
